### PR TITLE
Don't break the OSD on MiST with too long settings, delete redundant …

### PR DESCRIPTION
**Pull request by gyurco**
…files

2 Player Coins: 1 Credit/2 Players
is too long, and breaks the OSD on MiST.
If it's not acceptable to cut the setting name, then probably the MRA tool could do it (but it would be hard to make sure the truncation will happen in a sane position).

### CODE REVIEW

**Comment by gyurco** [comment]
I also noticed that you have to rename the released binary RBFs, but the needed new name is only at the MRA (ARC) file. This may confuse users. Maybe a link with the necessary name can be provided in the repo, pointing to the latest release.

**Comment by jotego** [comment]
[mra-tool.zip](https://github.com/jotego/jtbin/files/4604175/mra-tool.zip)

I think these are problems that occured only because of an old MRA tool. The latest one will take the RBF name from the MRA. If I have done everything correctily, the names for MiST cores checked in should be the ones expected in the ARC file.

It's true that the RBF files have been checked in with the timestamp in the name and that needs renaming. But only to delete the timestamp. I think I'll change the flow so it checks in a zip file with the timestamp but inside a core with the name without timestamp.

Thank you for the PR, but it might not be needed. Please try with the attached mra tool (for linux)

**Comment by gyurco** [comment]
This mra-tool filters out the long options (don't know if it is a good idea to drop them?). I hope it'll be in Seb's repo soon.
PS: I think those two deleted MRAs in the patch are still redundant.

**Comment by retrofun** [comment]
And there is a third redundant MRA: sectionz.mra.

**Comment by eubrunosilva** [comment]
and how about to have an altids? and tool export that ones to arc?
so who makes the mra takes cares of that.
whats the max size for each id?

**Comment by jotego** [comment]
@eubrunosilva The MRA tool uses the **alt** attribute of the RBF to get the right name in the ARC file.
@retrofun thank you, it is deleted now

**Pull request closed without merging**
