### PR TITLE
Update setnames for Black Tiger/Black Dragon according to MAME

### PR DESCRIPTION
**Pull request by Toryalai1**

### CODE REVIEW

**Comment by jotego** [comment]
I think you have misplaced the `_Black Tiger` folder. It should be inside the `_alternatives` folder

**Comment by Toryalai1** [comment]
True, Sorry about that. Will open a new pull request

**Comment by jotego** [comment]
You don't need to open one. If you make a new commit in your branch and push it, it will show up here.

**Comment by Toryalai1** [comment]
Yeah I will try that. Thanks

**Comment by Toryalai1** [comment]
I couldn't push to this pull request for some reason. It created a new one. Sorry

**Pull request closed without merging**
